### ISSUE TITLE
US25 - Configuração dos tresholds na geração das releases

### ISSUE THREAD

**Issue by Giuulob89** [fga-eps-mds/2023-1-MeasureSoftGram-Doc#101]
## Descrição da Issue
**Eu, como** Valéria
**Gostaria de** definir os valores de referência das medidas durante o planejamento de release
**Afim de** conseguir definir os valores segundo minhas preferências

## Critérios de Aceitação:
- [ ] No planejamento de releases, deve existir uma etapa nova opcional, que permita mudar os limites inferiores e superiores dos valores de referência
- [ ] Limites que são fixos não podem ser editáveis
- [ ] O sistema deve exibir uma mensagem de aviso caso o usuário tente editar um valor fixo.
- [ ] Deve haver uma explicação e um link para a documentação sobre os valores de referência.
- [ ] As definições dos valores de referência da configuração da última release devem estar disponíveis para poder ser reutilizada no planejamento da próxima release
- [ ] O sistema deve manter os valores definidos em sessão quando o usuário clicar nos botões de voltar ou continuar. 
- [ ] O sistema deve informar o usuário sobre as referências da literatura em qualidade de software utilizadas para a definição dos valores de referências e alerta-lo sobre os riscos da alteração.

**Observação**: Os cálculos feitos durante a release que foi planejada, devem seguir os limites definidos nessa etapa

## Protótipos

- https://www.figma.com/file/SUDrpsX09BJr6hLivq5Mte/MeasureSoftwareGram?type=design&node-id=1751%3A2587&t=O1oaosLflNdAjAZC-1

**Comment by hneri** [comment]
Ajustes na escrita da us:

Eu, como Valéria
Gostaria de definir os valores de referência das medidas durante o planejamento de release
A fim de conseguir definir os valores segundo minhas preferências

**Comment by hneri** [comment]
Ajustes nos critérios de aceitação:
- [ ] No planejamento de releases, deve existir uma etapa nova opcional, que permita mudar os limites inferiores e superiores dos valores de referência
- [ ] Limites que são fixos não podem ser editáveis
- [ ] O sistema deve exibir uma mensagem de aviso caso o usuário tente editar um valor fixo.
- [ ] Deve haver uma explicação e um link para a documentação sobre os valores de referência.
- [ ] As definições dos valores de referência da configuração da última release devem estar disponíveis para poder ser reutilizada no planejamento da próxima release
- [ ] O sistema deve manter os valores definidos em sessão quando o usuário clicar nos botões de voltar ou continuar. 
- [ ] O sistema deve informar o usuário sobre as referências da literatura em qualidade de software utilizadas para a definição dos valores de referências e alerta-lo sobre os riscos da alteração.

**Comment by hneri** [comment]
Transformar em observação: Os cálculos feitos durante a release que foi planejada, devem seguir os limites definidos nessa etapa. Não há como validar esse critério nesta história.

**Comment by hneri** [comment]
Dúvida:
O protótipo sugere que os valores min e max sejam inteiros. Como será possível inserir um número decimal?

**Comment by murilogds** [comment]
Bom dia @hneri , ajustes feitos, sobre a dúvida dos min e max decimais, ajustamos o protótipo para permitir a inserção de números decimais

**Comment by hneri** [comment]
Bom dia @murilogds. Conferi o protótipo. Pode considerar validado.
