### ISSUE TITLE
Adicionar `Agenda de trabalho e ferramentas`

### ISSUE THREAD

**Issue by higton** [fga-eps-mds/2023-1-MeasureSoftGram-Doc#14]
## Tarefas:

- [ ] Definir as timeboxes 
- [ ] Quadro de disponibilidade e de conhecimentos da equipe
- [ ] Ferramentas utilizadas pela equipe
- [ ] Quadro de Gantt

**Comment by SwampTG** [comment]
Farei o quadro de Gantt caso ninguém esteja fazendo agora.

**Comment by DaviMatheus** [comment]
Estou organizando o doc aqui, caso tena terminado o quadro pode enviar para eu adicionar aqui
