### ISSUE TITLE
US1: Permitir inserir treshold via interface CLI

### ISSUE THREAD

**Issue by higton** [fga-eps-mds/2023-1-MeasureSoftGram-Doc#20]
## Descrição da Issue
Eu, Paulo, gostaria de alterar os valores de referência(min, max) das medidas do modelo, via interface CLI (Command Line Interface), para personalizar essas variáveis segundo minhas preferências.

**Tarefas:**
- [x] Realizar testes de unidade e integração para garantir a funcionalidade;
- [x] Atualizar a documentação do CLI para incluir os novos comandos e suas respectivas funcionalidades;
- [x] Modificar core para aceitar as modificações do threshold.

**Critérios de Aceitação:**
- [x] O usuário deve ser capaz de inserir o treshold no msgram.json;
- [x] As mudanças realizadas nas configurações devem ser persistidas e refletidas nas operações subsequentes do sistema;
- [x] A documentação do CLI deve ser atualizada e fornecer informações claras sobre os novos comandos e suas funcionalidades.
- [x] Os thresholds podem ser modificados apenas no eixo X
- [x] Os thresholds(min, max) não podem ser iguais
- [x] O sistema deve apresentar uma mensagem de erro, caso os valores informados não pertençam ao conjunto dos números reais positivos, e de sucesso, no caso contrário.
- [x] Os valores de referência podem ser fornecidos em escala razão ou decimal.

**Comment by hneri** [comment]
Ajustando,
Eu, Paulo, gostaria de alterar os valores de referência(min, max) das medidas do modelo, via interface CLI (Command Line Interface), para personalizar essas variáveis segundo minhas preferências.
OBS: Os valores de referência são definidos por padrão, segundo modelos de qualidade definidos na literatura da engenharia de software.

**Comment by hneri** [comment]
Favor acrescentar esse critério de aceitação:
- os valores de referência podem ser fornecidos em escala razão ou decimal.
- o sistema deve apresentar uma mensagem de erro, caso os valores informados não pertençam ao conjunto dos números reais positivos, e de sucesso, no caso contrário.

**Comment by hneri** [comment]
Favor excluir esse critério de aceitação: O sistema deve apresentar mensagens de sucesso ou erro, dependendo dos valores do threshold;

**Comment by hneri** [comment]
Dúvida: quais seriam os comandos? Precisamos definir.

**Comment by marcosgtavares** [comment]
A principio pensamos que so editar o msgram.json seria suficiente. A segunda task ficou um pouco confusa quanto a isso, sendo que a ideia dela era atualizar a documentação sobre os campos de threshold no .json.

**Comment by hneri** [comment]
Entendi @marcosgtavares. Eu estava em dúvida, pois no meu entendimento, a ideia era exatamente fazer a edição do arquivo msgram.json.
