### ISSUE TITLE
US4: Permitir balanceamento das métricas de forma dinâmica na geração de release

### ISSUE THREAD

**Issue by higton** [fga-eps-mds/2023-1-MeasureSoftGram-Doc#23]
## Descrição da Issue
Eu, Valéria, gostaria de poder balancear as minhas metas de forma unitária, sem depender de relação com outras métricas, a fim de ter a facilidade de manuseio das metas de acordo com as minhas necessidades principais de uma release.

**Tarefas:**

- [ ] Realizar testes de unidade e integração para garantir a funcionalidade;
- [ ] Documentar funcionalidade de geração de release;
- [ ] Adicionar opção de balancear metas dinamicamente na geração de release;
- [ ] Remover comportamento de balancear as metas proporcionalmente quando a opção acima estiver desmarcada;

**Critérios de Aceitação:**

- [ ] O usuário deve ser capaz de manusear as metas de forma unitária;
- [ ] Os valores definidos pelo usuário devem ser respeitados ao gerar a release;
- [ ] Ao desmarcar a opção, as metas devem voltar a serem balanceadas proporcionalmente;
- [ ] Todos os testes devem passar;
- [ ] Deve existir uma nova documentação sobre o processo de geração de release, explicando essa etapa;

**Protótipo:**

- https://www.figma.com/file/SUDrpsX09BJr6hLivq5Mte/MeasureSoftwareGram?type=design&node-id=1751%3A2587&t=x5GNnC2SbvpUA9ij-1
- https://www.figma.com/file/SUDrpsX09BJr6hLivq5Mte/MeasureSoftwareGram?type=design&node-id=1751%3A2587&t=O1oaosLflNdAjAZC-1

**Comment by Giuulob89** [comment]
Substituída pela #89, que foi validada pelo cliente
