### ISSUE TITLE
US5: Não permitir acesso irrestrito ao site

### ISSUE THREAD

**Issue by higton** [fga-eps-mds/2023-1-MeasureSoftGram-Doc#25]
## Descrição da Issue
Eu como **Valeria, Paulo ou Miguel** eu não gostaria que os dados persistidos pelo sistema fossem acessados por alguém que não tem permissão, para que todos os usuários tenham que se autenticar(fazer login).

## Tarefas:
- [ ] Realizar testes de unidade e integração para garantir a funcionalidade.
- [ ] Modificar o Service para que as rotas sejam acessadas apenas pelo usuário logado.
- [ ] Refatorar as urls que estão no service

## Critérios de Aceitação:
- [ ] Não permitir que alguem consiga acessar qualquer informação dos produtos sem estar com uma conta logada no sistema.
- [ ] Caso o usuário não esteja autenticado, o sistema deve exibir uma mensagem de erro e redirecionar para a página de login.

**Comment by hneri** [comment]
Favor incluir o seguinte critério de aceitação: caso o usuário não esteja autenticado, o sistema deve exibir uma mensagem de erro e redirecionar para a página de login.

**Comment by SwampTG** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MeasureSoftGram-202301-6430cbdd6a89a7001a898a9c/issues/fga-eps-mds/2023-1-MeasureSoftGram-Doc/25?planning-poker) with Zenhub @igorq937

**Comment by SwampTG** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MeasureSoftGram-202301-6430cbdd6a89a7001a898a9c/issues/fga-eps-mds/2023-1-MeasureSoftGram-Doc/25?planning-poker) with Zenhub @higton
