### ISSUE TITLE
US6: Criar parser genérico

### ISSUE THREAD

**Issue by higton** [fga-eps-mds/2023-1-MeasureSoftGram-Doc#27]
## Descrição da Issue
Eu como Paulo, Valeria, Miguel ou Amanda, gostaria de extrair métricas de software em diferentes fontes de informação, para conseguir quantificar medidas associadas à diferentes características e subcaracterísticas da qualidade.

## Tarefas:
- [x] Pesquisar melhor ferramenta para realização do Parser
- [x] Análise das estruturas de arquivo ou retorno de API de diferentes plataformas de análise de código fonte
- [x] Criar uma modulo para realização do parser das plataformas
- [x] Realizar o import desses módulos nos projetos atuais a fim de padronizar o sistema de parser 
- [x] Adicionar as plataformas de análise de código fonte como plugin para o modulo.

## Critérios de Aceitação:
- [ ] Deve aceitar a entrada de arquivos em diferentes formatos(ex: .json; .xml; .csv) e fornecidos por diferentes fontes de informação, suportadas (ex: sonar, github, gitlab, jira).
- [ ] Deve ser possível configurar uma nova fonte de extração informação, sem a necessidade de alteração do mecanismo principal de extração. Deve ser possível estender o mecanismo de extração utilizando alternativas como, por exemplo, plugins ou adaptadores.
- [ ] Deve aceitar a extração de métricas via chamada a uma API.

**Comment by hneri** [comment]
Revisão e validação: @luisgfmarques @DaviMatheus 

Eu como Paulo, Valeria, Miguel ou Amanda, gostaria de extrair métricas de software em diferentes fontes de informação, para conseguir quantificar medidas associadas à diferentes características e subcaracterísticas da qualidade.

- deve aceitar a entrada de arquivos em diferentes formatos(ex: .json; .xml; .csv) e fornecidos por diferentes fontes de informação, suportadas (ex: sonar, github, gitlab, jira).
- deve ser possível configurar uma nova fonte de extração informação, sem a necessidade de alteração do mecanismo principal de extração. Deve ser possível estender o mecanismo de extração utilizando alternativas como, por exemplo, plugins ou adaptadores.
- deve aceitar a extração de métricas via chamada a uma API.

**Comment by luisgfmarques** [comment]
@hneri , US editada com as alterações solicitadas
