### ISSUE TITLE
US14: Criação da action do Github

### ISSUE THREAD

**Issue by higton** [fga-eps-mds/2023-1-MeasureSoftGram-Doc#38]
## Descrição da Issue
Eu, Amanda, gostaria de analisar a qualidade de uma versão de produto de software, para auxiliar minha decisão sobre as ações de melhoria a serem realizadas, em tempo de desenvolvimento.

OBS: uma versão de produto deve ser aferida ao fechar um pull request ou ao gerar uma release.    

**Tarefas:**
- [x] Criar action customizada que utiliza javascript
- [x] Action criar comentário no pull request
- [x] Usar os comandos da CLI para gerar o calculo
- [x] Permitir que o usuário altere as configurações a partir do input da action
- [x] Documentar sobre a action
- [x] Criar pipelines no novo repositorio

**Critérios de Aceitação:**
- [ ] Deve ser possível realizar os cálculos do measuresoftgram via pipeline do Github.
- [ ] A action deve conseguir coletar as métricas do Sonarqube, e a partir delas, usar o MSG para quantificar a percepção da qualidade.
- [ ] O output da action são os indicadores das características e do nível mais agregado, na perspectiva quantitativa da qualidade total (SQC). 
- [ ] Ao executar a action, o output deve ser exibido em um comentário da pull request, de forma parecida como o Sonarcloud faz atualmente, o resultado output da action (badges).
- [ ] Deve ser possível alterar as configurações do MSG a partir de um json.
- [ ] A action deve ser publicada no marketplace do github.
- [ ] A documentação do github Marketplace deve ser atualizada e fornecer informações claras sobre como criar uma action na pipeline do Github.

**Comment by hneri** [comment]
Segue a validação desta história. Ajustes: @higton 

Eu, Amanda, gostaria de analisar a qualidade de uma versão de produto de software, para auxiliar minha decisão sobre as ações de melhoria a serem realizadas, em tempo de desenvolvimento.

OBS: uma versão de produto deve ser aferida ao fechar um pull request ou ao gerar uma release.

Critérios de Aceitação:
-  deve ser possível realizar os cálculos do measuresoftgram via pipeline do Github.
- a documentação do CLI deve ser atualizada e fornecer informações claras sobre como criar uma action na pipeline do Github.
-  a action deve conseguir coletar as métricas do Sonarqube, e a partir delas, usar o MSG para quantificar a percepção da qualidade.
- o output da action são os indicadores das características e do nível mais agregado, na perspectiva quantitativa da qualidade total (SQC). 
- ao executar a action, o output deve ser exibido em um comentário da pull request, de forma parecida como o Sonarcloud faz atualmente, o resultado output da action (badges).
- as informações dos cálculos devem ser persistidas no banco, em todos os níveis do modelo
- deve ser possível alterar as configurações do MSG a partir de um json.
- a action deve ser publicada no marketplace do github.
