### ISSUE TITLE
US21: Armazenar as informações da action do Github

### ISSUE THREAD

**Issue by higton** [fga-eps-mds/2023-1-MeasureSoftGram-Doc#51]
## Descrição da Issue
Eu, Amanda, gostaria de utilizar a interface gráfica para analisar a qualidade de uma versão de produto de software a partir das informações geradas pela action do github.

## Tarefas:
- [ ] Criar endpoint no service para a action armazenar os cálculos
- [ ] Modificar a action para usar o novo endpoint
- [ ] Implementar lógica na action para verificar se alguma release está em desenvolvimento
- [ ] Documentar no readme sobre as novas mudanças

## Critérios de Aceitação:
- [ ]  Deve ser possível visualizar as informações geradas pelo cálculo do pipeline por meio da interface gráfica (web) já existente.
- [ ]  A interface deve possibilitar a visualização das informações geradas pelo cálculo na action, em todos os níveis do modelo: métricas; medidas; subcaracterísticas; características e agregado(sqc).
- [ ] Caso a data de fim da release em desenvolvimento seja menor que a data da execução da action, deve ser apresentada uma mensagem de erro e suspendida a execução da action.
- [ ] A interface deve disponibilizar um token de acesso para o usuário usar na action.
- [ ] Atualizar a documentação no marketplace da action.

## Protótipos
Foi criado um protótipo de baixa fidelidade, com algumas opções de como o usuário poderia pegar este token.

![Diagrama sem nome drawio (1)](https://github.com/fga-eps-mds/2023-1-MeasureSoftGram-Doc/assets/37488154/d3f211b8-b916-496f-b995-9363b22fd0a2)

**Comment by hneri** [comment]
Ajustes:
Eu, Amanda, gostaria de persistir as informações geradas por meio da action do github, que realiza os cálculos do modelo, para poder analisar uma versão de produto de software, a partir da interface gráfica (web).

Critérios de aceitação:
- Deve ser possível visualizar as informações geradas pelo cálculo do pipeline por meio da interface gráfica (web) já existente.
- A interface deve possibilitar a visualização das informações geradas pelo cálculo na action, em todos os níveis do modelo: métricas; medidas; subcaracterísticas; características e agregado(sqc).
- Caso a data de fim da release em desenvolvimento seja menor que a data da execução da action, deve ser apresentada uma mensagem de erro e suspendida a execução da action.
- Atualizar a documentação no marketplace da action.
