### ISSUE TITLE
US22: Adicionar botão para desbloquear sliders ao definir metas de qualidade

### ISSUE THREAD

**Issue by murilogds** [fga-eps-mds/2023-1-MeasureSoftGram-Doc#89]
## Descrição da Issue
**Eu, como** Valéria
**Gostaria de** poder desabilitar a relação entre as características de qualidade durante o planejamento de uma release
**Afim de** não depender das evidências da literatura em qualidade de software sobre as relações.
## Tarefas:
- [x] Criar checkbox que desbloqueie sliders
- [x] Criar modal que explica o que ela faz

## Critérios de Aceitação:
- [ ] Ao clicar na checkbox, o usuário deve conseguir configurar livremente as características de qualidade, podendo mexer individualmente em cada uma.
- [ ] Ao clicar na checkbox, antes de liberar os sliders, o sistema deverá mostrar um aviso para o usuário explicando a relação entre as métricas, segundo a literatura em qualidade de software e os riscos de ignorá-las.

**Observação**: Ao terminar de definir a meta de qualidade, o planejamento da release deve ser finalizado, e, com isso, a action dos repositórios do produto em que foi definida a release deve seguir as configurações definidas nessa release.

## Protótipos
- https://www.figma.com/file/SUDrpsX09BJr6hLivq5Mte/MeasureSoftwareGram?type=design&node-id=1751%3A2587&t=x5GNnC2SbvpUA9ij-1

**Comment by hneri** [comment]
Ajustes na escrita
Eu, como Valéria
Gostaria de poder desabilitar a relação entre as características de qualidade durante o planejamento de uma release
A fim de não depender das evidências da literatura em qualidade de software sobre as relações.

**Comment by hneri** [comment]
Critérios de Aceitação:
- [ ] Ao clicar na checkbox, o usuário deve conseguir configurar livremente as características de qualidade, podendo mexer individualmente em cada uma.
- [ ] Ao clicar na checkbox, antes de liberar os sliders, o sistema deverá mostrar um aviso para o usuário explicando a relação entre as métricas, segundo a literatura em qualidade de software e os riscos de ignorá-las.

**Comment by hneri** [comment]
Transformar em observação. Não há como validar esse critério, nesta história.
OBS: Ao terminar de definir a meta de qualidade, o planejamento da release deve ser finalizado, e, com isso, a action dos repositórios do produto em que foi definida a release deve seguir as configurações definidas nessa release
