### ISSUE TITLE
Gráfico de comportamento das característitcas da release atual

### ISSUE THREAD

**Issue by igorq937** [fga-eps-mds/2023-1-MeasureSoftGram-Doc#99]
## Descrição da Issue
Atualmente, os gráficos que mostram o comportamento das características da release mais recente de um repositório estão localizados em um local menos visível. Essa tarefa tem como objetivo movê-los para o topo da página do repositório, tornando-os mais acessíveis aos usuários.

## Tarefas:
- [ ] Mover os gráficos das características da versão atual do repositório para o topo da página do repositório, de forma que fiquem imediatamente visíveis aos usuários.
- [ ] Aprimorar a visualização dos gráficos, tornando-os mais claros e informativos.
- [ ] Melhorar a descrição dos gráficos, fornecendo informações adicionais sobre as características representadas e como interpretar os dados exibidos.

## Critérios de Aceitação:
- [ ] A descrição dos gráficos foi aprimorada para fornecer informações adicionais sobre as características representadas e orientar a interpretação dos dados exibidos.
- [ ] Os gráficos foram organizados de maneira a não consumir todo o espaço de tela disponível, permitindo que outras informações relevantes também sejam exibidas.
- [ ] Os gráficos são atualizados dinamicamente de acordo com os filtros já existentes na página de repositório, fornecendo uma visualização precisa das características com base nas seleções do usuário.

### v3 - final
![Selecionar Características v2 (1)](https://github.com/fga-eps-mds/2023-1-MeasureSoftGram-Doc/assets/71738659/eeac9221-1263-45e1-ab85-e5bb899fa697)

### v2
![Selecionar Características v2](https://github.com/fga-eps-mds/2023-1-MeasureSoftGram-Doc/assets/71738659/bc25c828-fe03-4ed8-b0b4-17aa2507ca31)

### v1
![image](https://github.com/fga-eps-mds/2023-1-MeasureSoftGram-Doc/assets/30667234/7d333f56-257f-443b-9355-71a241bf2d01)

**Comment by hneri** [comment]
Considerações:
- o leiaute do gráfico MSG atualmente implementado não precisa ser modificado. Ele precisa ser movido para o topo e melhorado, de maneira a não consumir todo o espaço de tela.
- o gráfico do MSG deve exibir os dados históricos, ao longo do tempo, não somente da release atual.
- o gráfico do MSG deve utilizar o filtro existente.
- o segundo gráfico (todas as características) não deve mais ser exibido automaticamente. Por favor, pensem em uma forma do usuário poder escolher os tipos de gráficos, considerando que serão diferentes visualizações (linha, gauge, radar,...)

**Comment by CarlosFiuza** [comment]
![Selecionar Características v2](https://github.com/fga-eps-mds/2023-1-MeasureSoftGram-Doc/assets/71738659/bc25c828-fe03-4ed8-b0b4-17aa2507ca31)

De acordo com as considerações acima, criamos essa segunda versão do protótipo, adicionando:

- Gráfico "Cenário atual das Características": apresenta os valores mais recentes das características filtradas;
    - Possui tab vertical na lateral esquerda que pode ser usada para mudar o tipo de gráfico apresentado, nesse caso o de radar e de gauge.
    - Por conta da natureza de visualização dos gráficos de radar e de gauge, não será possível apresentar multiplos dados no tempo, por isso o gráfico trataria apenas dos valores mais recentes.
- Gráfico "Histórico das Características": apresenta os valores das características filtradas através do tempo:
    - Possui tab vertical na lateral esquerda que pode ser usada para mudar o tipo de gráfico apresentado, nesse caso o MSG (gráfico similar ao de eletrocardiograma que apresenta linhas individuais para cada característica) e o de linha (gráfico atual de "Características").
    - O espaçamento entre as linhas será diminuido a fim de não comprometer a tela inteira

**Comment by hneri** [comment]
Ótimo! Por fim, sugiro mudar: 
1) inverter as posições dos gráficos, histórico(linhas) antes do radar e gauge;
2) alterar o título da tabela [Última atualização] para [Última medição];
3) o último botão de download não é necessário. O botão precisa estar logo abaixo do gráfico dos históricos e realizar o download dos dados, a partir da opção de filtro.

**Comment by CarlosFiuza** [comment]
Certo, modificações aplicadas.
![Selecionar Características v2 (1)](https://github.com/fga-eps-mds/2023-1-MeasureSoftGram-Doc/assets/71738659/eeac9221-1263-45e1-ab85-e5bb899fa697)

**Comment by hneri** [comment]
Obrigado, @CarlosFiuza e @igorq937 !
